[application]

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "assets"

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "Plane-S Structural Analysis"

[web.watcher]

index_on_404 = true

watch_path = ["src", "assets", "index.html"]

[bundle]
# Bundle identifier
identifier = "io.github.plane-s"

# Bundle publisher
publisher = "plane-s"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["public/*"]

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "An amazing dioxus application."

# Bundle long description
long_description = """
An amazing dioxus application.
"""
